require: rubocop-rails

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 80
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Exclude:
    - '**/**/*_spec.rb'
    - '**/support/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - '**/**/*_spec.rb'
    - '**/support/**/*.rb'
    - '**/shared_examples/*.rb'
Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
    - include
    - prepend
    - extend
  ExpectedOrder:
  - module_inclusion
  - constants
  - public_class_methods
  - initializer
  - public_methods
  - protected_methods
  - private_methods
Layout/DotPosition:
  EnforcedStyle: leading
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Style/AndOr:
  EnforcedStyle: conditionals
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
Style/NumericPredicate:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: true
Rails/LexicallyScopedActionFilter:
  Enabled: false
AllCops:
  DisplayCopNames: true
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/schema.rb'
  - 'db/seeds.rb'
  - 'lib/tasks/cucumber.rake'
  - 'script/cucumber'
  - 'tmp/**/*'
  - 'vendor/**/*'
  - 'Rakefile'
  - 'Gemfile'
  - 'spec/dummy/bin/**/*'
  - 'spec/dummy/db/schema.rb'
  - 'spec/dummy/config/**/*'
  - 'spec/dummy/script/**/*'
  - 'spec/spec_helper.rb'
  - 'spec/rails_helper.rb'
  - 'features/**/*'
  - 'node_modules/**/*'